### ISSUE TITLE
Contradictory behavior between Smrnmi and Smdbltrp extensions

### ISSUE THREAD

**Issue by franhans** [riscv/riscv-double-trap#33]
Hi,

Thinking in the implementation of the Smdbltrp extension I have found that the Smrnmi extension and the Smdbltrp propose two different behaviors for the same situation where mnstatus.NMIE bit is 0.

Here is what is proposed in the Smdbltrp extension:
```
When the Smrnmi extension is not implemented, or if the Smrnmi extension is implemented and mnstatus.NMIE is 0, the hart enters a critical-error state without updating any architectural state including the pc. This state involves ceasing execution, disabling all interrupts (including NMIs), and asserting a critical-error signal to the platform.
```
and here in the Smrnmi extension:
```
If the hart encounters an exception while executing in M-mode with the mnstatus.NMIE bit clear, the actions taken are the same as if the exception had occurred while mnstatus.NMIE were set, except that the program counter is set to the RNMI exception trap handler address (rather than the address specified by mtvec).
```

What happens when both extensions are implemented? Does the Smdbltrp behavior take precedence over the Smrnmi extension?

Thank you very much!
Kind regards.

**Comment by ved-rivos** [comment]
> What happens when both extensions are implemented? Does the Smdbltrp behavior take precedence over the Smrnmi extension?

The behavior specified by Smdbltrp takes precedence over the Smrnmi.
