### ISSUE TITLE
Compatibility of Smdbltrp with existing nested interrupt handling software

### ISSUE THREAD

**Issue by Wren6991** [riscv/riscv-double-trap#37]
Hi,

My question is about Smdbltrp, in the context of nested interrupt handling on low-end (say M-mode-only) implementations, using either a PLIC or custom interrupt controller. For simplicity let's assume Smrnmi is not implemented. The spec in this repository says:

> When a trap is to be taken into M-mode, if the MDT bit is currently 0, it is then set to 1, and the trap is
delivered as expected. However, if MDT is already set to 1, **then this is an unexpected trap**

Noting that "trap" as defined in the unprivileged ISA manual includes both interrupts and exceptions, this seems to cover interrupts too:

> We use the term exception to refer to an unusual condition occurring at run time associated with an instruction in the current RISC-V hart. We use the term interrupt to refer to an external asynchronous event that may cause a RISC-V hart to experience an unexpected transfer of control. We use the term trap to refer to the transfer of control to a trap handler caused by either an exception or an interrupt. 

A nested interrupt handler may do some steps like the following:

1. Save critical state like `mstatus`, `mepc`, previous preemption threshold
1. Set new preemption threshold, then re-enable IRQs
1. Save GPRs (note, since `__attribute__((interrupt))` unfortunately adds an `mret`, it's common to use C calling convention for ISRs called under soft dispatch)
1. Dispatch handlers within current trap frame, repeating until there are no active IRQs at or above the previous preemption threshold sampled during critical save section
1. Restore GPRs
1. Disable IRQs for critical restore
1. Restore return state, then `mret`

Based on the spec paragraph above, I think the intention is that the clearing of MDT is added to the critical restore section in bullet point 1. So my questions are:

1. Am I correct in understanding that, if you do not do this, any existing use of nested IRQs like the above will produce a critical error condition, and therefore break fatally on new hardware that implements Smdbltrp?
1. Is there some small change to the spec that would avoid breaking existing software in this way, like gating the automatic setting of MDT based on another CSR bit?

Another common pattern that may be affected is the "on error resume next"-style exception handling used for feature detection during startup. You see a lot of this in `riscv-tests`, for example:

https://github.com/riscv-software-src/riscv-tests/blob/408e461da11e0b298c4b69e587729532787212f5/debug/programs/entry.S#L29-L50

**Comment by ved-rivos** [comment]
Clearing of MDT is needed at step 1 if the handler expects there to be nested traps. If not then the `MRET` will clear `MDT`. The architecture does provide a opt-in control in `menvcfg` and `henvcfg` for code that is expected to be portable across platforms. In case of machine mode code, the machine mode code is expected to be intimately familiar with the machine and so was not motivated. Further for machine mode for robustness purposes the reset state of `MDT` is 1 to address concerns such as [this](https://github.com/riscv/riscv-isa-manual/pull/1178). For the riscv-tests like scenario where the handler does not unmask interrupts or raise further exceptions, the `MDT` can be left set and the subsequent `MRET` will clear the `MDT`.

**Comment by Wren6991** [comment]
> Clearing of MDT is needed at step 1 if the handler expects there to be nested traps.

Thanks for confirming.

> The architecture does provide a opt-in control in menvcfg and henvcfg for code that is expected to be portable across platforms.

And `menvcfg.dte` is specifically an opt-in for Ssdbltrp, with no effect on the operation of Smdbltrp? Just checking my understanding.

> In case of machine mode code, the machine mode code is expected to be intimately familiar with the machine and so was not motivated.

This is a fair point, embedded software is not expected to be distributed as portable binaries. At the source level though, the same codebases are stretched across many years of RISC-V ISA development and more differences means more bugs. I think preserving compatibility with existing software where possible is a good motivation in itself.

> For the riscv-tests like scenario where the handler does not unmask interrupts or raise further exceptions, the MDT can be left set and the subsequent MRET will clear the MDT.

In the example I posted there *is no* `mret`. The exception path silently skips the code which experienced the exception, making it conditional on the relevant extension or CSR having been implemented. There may be multiple such constructs in a row, so one may trap using another's MDT, and experience a critical error. Here is another example of that pattern, also from `riscv-tests`: https://github.com/riscv-software-src/riscv-tests/blob/408e461da11e0b298c4b69e587729532787212f5/benchmarks/common/crt.S#L70-L106

**Comment by ved-rivos** [comment]
> And menvcfg.dte is specifically an opt-in for Ssdbltrp, with no effect on the operation of Smdbltrp? Just checking my understanding.

That is right. 

> At the source level though, the same codebases are stretched across many years of RISC-V ISA development and more differences means more bugs. I think preserving compatibility with existing software where possible is a good motivation in itself.

Since `MDT` is a WARL field, the source code can be updated to unconditionally clear the `MDT` and it will be backward compatible with implementations that do not support Smdbltrp and so should not prevent having a single source base.

**Comment by Wren6991** [comment]
> Since MDT is a WARL field, the source code can be updated to unconditionally clear the MDT and it will be backward compatible with implementations that do not support Smdbltrp and so should not prevent having a single source base.

Ok, thanks, this resolves the concrete problem for me. I guess the riscv-tests stuff will get fixed if somebody hits it.
