### ISSUE TITLE
Question about the double trap that occurs as a result of an interrupt

### ISSUE THREAD

**Issue by nonufrienko** [riscv/riscv-double-trap#39]
I have doubts about understanding the following scenario:

1. In M-mode, write 1 to `mstatus.MDT`.
2. Switch to S-mode or U-mode using the `SRET` instruction instead of the `MRET` instruction to keep `MDT=1`.
3. An interrupt occurs that is taken into M-mode. However, since the value of `MDT` is 1, this interrupt results in unexpected trap.
4. If the `Smrnmi` extension is implemented and `mnstatus.NMI` equals 0, then control is transferred to the RNMI handler.
However, the value written to `mncause` in this case will have 1 in the most significant bit and may coincide with existing NMI cause codes.

In section `8.3. RNMI CSRs` of the [privileged ISA](https://github.com/riscv/riscv-isa-manual/releases/tag/riscv-isa-release-c8c8075-2024-06-12), only a double trap, which is the result of an exception, is mentioned:
```
If the reason is an exception within M-mode that results in a double trap as specified in the Smdbltrp extension, bit MXLEN-1 is set to 0 and the least-significant bits are set to the cause code corresponding to the exception that precipitated the double trap.
```

However, the description of the Smdbltrp extension refers to any trap:
```
When the Smrnmi extension is implemented and mnstatus.NMIE is 1, the hart traps to the RNMI handler. To deliver this trap, the mnepc and mncause registers are written with the values that the unexpected trap would have written to the mepc and mcause registers respectively. The privilege mode information fields in the mnstatus register are written to indicate M-mode and its NMIE field is set to 0.
```

Do I understand correctly that the interrupt in this case leads to a double trap?

How should software distinguish this scenario in the RNMI handler from a regular Resumable NMI?

**Comment by ved-rivos** [comment]
The `SRET` instruction should have been specified to also set `MDT` to 0. Thanks for spotting that. Updated in #41 .

**Comment by nonufrienko** [comment]
Switching to another privilege mode with MDT set to 1 is also possible using the DRET instruction in debug mode.

From [RISC-V Debug Specification](https://github.com/riscv/riscv-debug-spec/releases/tag/1.0.0-rc3):
```
When dret is executed, is restored from dpc and normal execution resumes at the privilege set by prv and v.
```

<br>
<br>
Is it even supposed to be possible to take a double trap as a result of an interrupt?

**Comment by ved-rivos** [comment]
> Is it even supposed to be possible to take a double trap as a result of an interrupt?

No. The debugger should not be allowed to cause this. The resume from Debug Mode should clear the xDT based on the new privilege mode. Updated in #42

**Comment by nonufrienko** [comment]
Ok, thanks

**Comment by nonufrienko** [comment]
I'm sorry. What about the following case: In M mode, set sstatus.SDT to 1, then switch using MRET to U-mode. In U-mode, an interrupt occurs occurs that is taken into S-mode.

**Comment by ved-rivos** [comment]
Yes, that case needs to be addressed. I was in process of updating for that. Will share link to the update in a bit.

**Comment by ved-rivos** [comment]
Please see #43

**Comment by nonufrienko** [comment]
It looks fine, but there are doubts that SDT should be mentioned in the Smdbltrp section. 
<br>
<br>
P.S. It is also unclear why it is necessary to introduce Exception Code 16 into the implementation that supports only Smdbltrp.

**Comment by ved-rivos** [comment]
Mentioning SDT in Smdbltrp is fine. The exception code 16 is defined for this purpose - it will not be used for any other purpose in the ISA. It will be unused for Smdbltrp without Smrnmi implementation - this is no different than other exception codes like page-fault or guest-page-fault.

**Comment by nonufrienko** [comment]
> It will be unused for Smdbltrp without Smrnmi implementation
Ok, but then I missed how it would be used with Smrnmi. mncause is written with the exception code that caused the double trap.

**Comment by ved-rivos** [comment]
Its not used unless Ssdbltrp is implemented.

**Comment by nonufrienko** [comment]
Ok, then no more questions. Thanks.
