### ISSUE TITLE
Is it on purpose that .SDT is invisible from MSTATUS?

### ISSUE THREAD

**Issue by zengderui** [riscv/riscv-double-trap#46]
Since `SSTATUS` is a subset of `MSTATUS`, I'm wondering why `.SDT` is absent in `MSTATUS`.

**Comment by ved-rivos** [comment]
`sstatus` is a subset of `mstatus`. When a bit - such as `SDT` - is added to `sstatus` it is in `mstatus`.

**Comment by zengderui** [comment]
Hi @ved-rivos Thanks for your confirmation! I'm asking because I don't see `SDT` in the layout of  `mstatus`, which confuses me, see https://github.com/riscv/riscv-isa-manual/blob/main/src/images/wavedrom/mstatusreg.adoc

**Comment by ved-rivos** [comment]
@zengderui thanks for spotting that. I have have that updated in the ISA manual.
