### ISSUE TITLE
What is the impact of MNRET instruction on .MNPP?

### ISSUE THREAD

**Issue by zengderui** [riscv/riscv-double-trap#47]
Should `.MNPP` be set to the least-privileged supported mode on `MNRET` instruction as `.MPP` on `MRET` instruction?

**Comment by ved-rivos** [comment]
This question is not related to Smdbltrp. Could you please ask as an isa-manual issue or on the priv mail list.

**Comment by zengderui** [comment]
This is an RNMI-related question, I have created an issue on the ISA manual.
