### ISSUE TITLE
Question on double-trap caused by an external RNMI interrupt

### ISSUE THREAD

**Issue by zengderui** [riscv/riscv-double-trap#49]
The specification states that it is an _unexpected trap_ when the trap is to be taken into M-mode and `MDT` is already set to 1, could this trap be an RNMI interrupt asserted via an external input pin? 

If yes, what value should `mncause` be written? Is the `interrupt` field 1 and the `Exception Code` field implementation-defined?

**Comment by zengderui** [comment]
If I understand the spec correctly, the definition of an unexpected trap is
`trap-into-m-mode && ((MDT-is-1) || (RNMI-is-implemented && current-mode-is-m-mode && mnstatus.NMIE-is-0)`
so an RNMI is an unexpected trap when DMT is 1.

Your reply seems to say, when RNMI is implemented, the value of MDT doesn't determine if a trap is an unexpected trap. The formula becomes:
`trap-into-m-mode && (RNMI-is-implemented ? (current-mode-is-m-mode && mnstatus.NMIE-is-0) : MDT-is-1)`

Please point out if my understanding is wrong.

**Comment by ved-rivos** [comment]
Its => trap-into-m-mode && ((MDT=1 && ~RNMI) || (priv==M && NMIE is 0)).

**Comment by ved-rivos** [comment]
Perhaps a clarification will help make this clear by adding: An RNMI trap is not considered an _unexpected trap_.

**Comment by zengderui** [comment]
> Perhaps a clarification will help make this clear by adding: An RNMI trap is not considered an _unexpected trap_.

Yes, this clarification is helpful, please put it in the spec. The formula you provided confuses me😄.

**Comment by zengderui** [comment]
Please close this issue once that clarification is added.

**Comment by ved-rivos** [comment]
Clarification added in #51
