### ISSUE TITLE
Question on privilege mode info in mnstatus upon an unexpected trap when Smrnmi is implemented  and mnstatus.NMIE is 1

### ISSUE THREAD

**Issue by zengderui** [riscv/riscv-double-trap#50]
For _unexpected trap_ handling when `Smrnmi` is implemented and `mnstatus.NMIE` is 1, the specification says "The privilege mode information fields in the mnstatus register are written to indicate M-mode".

Does it imply that `mnstatus.MNPP` is set to 3 (M-mode) and `mnstatus.MNPV` is set to 0 regardless of the current privilege mode?
Normally the current privilege mode is M-mode, but it could be S-mode as a result of the following **strange** steps.

- Upon reset Hart is in M-mode and `mnstatus.MDT` is 1, set `mnstatus.MNPP` to 1 (S-mode)
- Execute `mnret` instruction, privilege mode changes from M-mode to S-mode, `mstatus.MDT` remains 1 (specification doesn't say `mnret` set `mstatus.MDT` to 0)
- Execute `ecall` instruction to raise an exception to M-mode, since `mstatus.MDT` is 1, this exception is an _unexpected trap_, current privilege mode is S-mode and the target mode is M-mode

Should `mnret` also sets the `MDT` bit to 0 when executed in M-mode?

**Comment by ved-rivos** [comment]
Yes. The `MNRET` instruction should set the `MDT` bit to 0, if the new privilege mode is not M. If it is U, VS, or VU, then `sstatus.SDT` should also be set to 0. Additionally, if it is VU, then `vsstatus.SDT` should also be set to 0.

**Comment by zengderui** [comment]
>> The MNRET instruction should set the MDT bit to 0, if the new privilege mode is not M
Will you put this sentence into the Double Trap spec? Or it should go to the RNMI spec?

**Comment by ved-rivos** [comment]
This will go into the double trap spec.
