### ISSUE TITLE
Double trap and Debug

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-double-trap#53]
Hi, 

I have some questions related to the interaction of the Double Trap extensions and Debug:

1. Why is cetrig defined as a R/W register instead of a WARL register (as many of the other bitfields in dcsr)?
2. When the hart is in 'critical-error state' and cetrig is 0 can Debug Mode still be entered due to for example a debug 'halt request' (to for example interrogate the state of the hart) and if so what will be the result of attempting 'single stepping'? (If single stepping is supported I would expect that the 'step' would simply never complete as the pc is frozen, which is probably fine)

Best regards,
Arjan

**Comment by ved-rivos** [comment]
@Silabs-ArjanB 
1. It should be WARL. Will fix that.
2. When the hart is in a critical-error state and cetrig is 0 then the hart will signal a critical-error to the platform. Whether the platform and hart support entering debug mode after the critical error has been signaled is unspecified and is platform specific. A hart is not required to support halting or single stepping when in critical-error state.The specified way to debug this state is to use cetrig to enter debug mode when the critical-error condition is detected.

**Comment by Silabs-ArjanB** [comment]
@ved-rivos Thank you for your quick reaction. That is clear. 

You can close this issue when you want.
