### ISSUE TITLE
Question about the relation between SIE and SDT

### ISSUE THREAD

**Issue by myx922** [riscv/riscv-double-trap#56]
I have some doubts about the relationship between sdt and sie described in the spec. Spec points out that if SDT is set to 1 or is already 1, SIE cannot be 1, and if menvcfg.DTE is zero, sstatus.SDT is read-only zero.
When menvcfg.DTE=0, mstatus.SDT is set to 1, I'm confused that if sstatus.SIE can be set to 1? And what about mstatus.SIE?
The spec state:
> When the SDT bit is set to 1 by an explicit CSR write, the SIE (Supervisor Interrupt Enable) bit is cleared to 0. This clearing occurs regardless of the value written, if any, to the SIE bit by the same write. The SIE bit can only be set to 1 by an explicit CSR write if the SDT bit is being set to 0 by the same write or is already 0.
> When menvcfg.DTE is zero, the implementation behaves as though Ssdbltrp is not implemented. When Ssdbltrp is not implemented sstatus.SDT, vsstatus.SDT, and henvcfg.DTE bits are read-only zero. When henvcfg.DTE is zero, the implementation behaves as though Ssdbltrp is not implemented for VS-mode and the vsstatus.SDT bit is read-only zero.

**Comment by ved-rivos** [comment]
`menvcfg.DTE` affects the operations at modes with privilege less than M. When `menvcfg.DTE` is 0 and privilege mode is less than M, `SDT` is read only **zero**. When `SDT` is zero, `SIE` can be set to 1.

**Comment by myx922** [comment]
I got it. Thank you for your reply.
