### ISSUE TITLE
critical-error state details

### ISSUE THREAD

**Issue by jscheid-ventana** [riscv/riscv-double-trap#9]
Is this to be entered synchronously at the point the trap would have been taken?

It would be clearer if PCERR is always valid, thus avoiding hidden state and allowing a debugger to poll without needing to enter debug mode.

Is there a need here to discuss hart behavior in "critical-error" state:

- allow for speculative accesses
- require eventual quiescence

**Comment by ved-rivos** [comment]
> Is this to be entered synchronously at the point the trap would have been taken?

Entering critical error state is not a trigger to enter debug mode.

> It would be clearer if PCERR is always valid, thus avoiding hidden state and allowing a debugger to poll without needing to enter debug mode.

Debuggers can read the dmcs2.PRR to determine if harts are in critical error state. When a hart enters debug mode from critical error state, it is not in a critical error state and instruction execution such as through the program buffer is allowed. The PCERR indicates that the hart was in critical error state before entering debug mode and on a resume places the hart back into critical error state.

> Is there a need here to discuss hart behavior in "critical-error" state:

This double trap condition detection occurs as part of the hardware sequence that performs trap delivery. When a double trap condition is detected, the trap is not delivered and instead the hardware causes the hart to enter the critical error state. This state involves suspending execution, disabling all interrupts (including NMIs), and asserting a platform-reset-request to the platform. 

Please say more about the eventual quiescence requirement.

**Comment by ved-rivos** [comment]
@jscheid-ventana - please let me know if your questions were addressed.
